#!/usr/bin/env python3
"""Crawl China Mobile (中国移动) tariff data from 资费专区 page.

The API responses are AES-CBC encrypted (key/iv generated by obfuscated JS),
so we render the page with headless Chromium and parse the DOM instead.

Page: https://h.app.coc.10086.cn/cmcc-app/pc-pages/tariffZonePers.html
Tabs: 个人资费/政企资费, 全网资费/北京资费; waterfall layout, no pagination.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SOURCE = "中国移动"
SOURCE_SHORT = "移动"
URL = "https://h.app.coc.10086.cn/cmcc-app/pc-pages/tariffZonePers.html"

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"


def extract_cards(page) -> list[dict[str, Any]]:
    """Parse waterfall cards from rendered DOM."""
    return page.evaluate(
        """() => {
        const cards = [];
        for (const node of document.querySelectorAll('.tariff-item-container')) {
            const text = node.innerText || '';
            if (text && !cards.includes(text)) cards.push(text);
        }
        if (cards.length === 0) {
            // fallback: split merged container text on 方案编号
            const stdEls = [...document.querySelectorAll('div')].filter(e =>
                (e.innerText||'').trim().startsWith('资费标准'));
            const seen = new Set();
            for (const el of stdEls) {
                let node = el;
                for (let i = 0; i < 8 && node; i++) {
                    const cls = (node.className||'').toString();
                    if (cls.includes('free-box') || (node.children.length >= 4 && (node.innerText||'').length > 3000)) break;
                    node = node.parentElement;
                }
                if (node) seen.add(node);
            }
            for (const node of seen) {
                const parts = (node.innerText||'').split(/\\n(?=资费标准:)/);
                for (const p of parts) { if (p.trim() && !cards.includes(p)) cards.push(p.trim()); }
            }
        }
        return cards;
    }"""
    )


def parse_card(text: str) -> dict[str, Any] | None:
    def grab(pattern: str) -> str:
        m = re.search(pattern, text, re.S)
        return m.group(1).strip() if m else ""

    name = grab(r"^([^\n]+)")
    fee_text = grab(r"资费标准:\s*([^\n]+)")
    report_no = grab(r"方案编号:\s*([^\n]+)")
    plan_type = grab(r"资费类型:\s*([^\n]+)")
    use_scope = grab(r"适用范围:\s*([^\n]+)")
    regions = grab(r"适用地区:\s*([^\n]+)")
    sale_channel = grab(r"销售渠道:\s*([^\n]+)")
    online = grab(r"上线日期:\s*([^\n]+)")
    offline = grab(r"下线日期:\s*([^\n]+)")
    valid = grab(r"有效期限:\s*([^\n]+)")
    stay = grab(r"在网要求:\s*([^\n]+)")
    breach = grab(r"违约责任:\s*([^\n]+)")
    broadband = grab(r"宽带\s*\n([^\n]+)")
    overage = grab(r"超出资费说明:\s*([^\n]+)")
    content = grab(r"其他服务内容:\s*([^\n]+)")
    others = grab(r"其他说明:\s*([^\n]+)")

    # service features: 国内通话 / 国内通用流量 / 定向流量 / 权益 / 短信
    voice = None
    traffic = None
    orient = None
    m = re.search(r"国内通话\s*\n(\d+(?:\.\d+)?)\s*分钟", text)
    if m:
        voice = float(m.group(1))
    m = re.search(r"国内通用流量\s*\n(\d+(?:\.\d+)?)\s*GB", text)
    if m:
        traffic = float(m.group(1))
    m = re.search(r"定向流量\s*\n(\d+(?:\.\d+)?)\s*GB", text)
    if m:
        orient = float(m.group(1))

    fee = None
    m = re.search(r"(\d+(?:\.\d+)?)\s*元/(月|次|年)", fee_text)
    if m:
        fee = float(m.group(1))

    if not name:
        return None
    service_content = " ".join(x for x in (content, others) if x)
    return {
        "source": SOURCE,
        "atomic_source_names": [SOURCE_SHORT],
        "plan_name": name,
        "report_no": report_no,
        "region": "全国" if "全网" in text else "北京",
        "plan_type": "流量包" if "加装" in plan_type or "包" in plan_type and "套餐" not in plan_type else "套餐",
        "monthly_fee": fee,
        "fee_text": fee_text,
        "general_traffic_gb": traffic,
        "orient_traffic_gb": orient,
        "voice_minutes": voice,
        "sms": None,
        "contract": is_contract(name, service_content + " " + fee_text),
        "contract_desc": contract_desc(name, service_content + " " + fee_text),
        "valid_period": valid,
        "sale_channel": sale_channel,
        "use_scope": use_scope,
        "overage": overage,
        "service_content": service_content,
        "online_date": online,
        "offline_date": offline,
        "raw_url": URL,
        "crawled_at": datetime.now(timezone.utc).isoformat(),
    }


CONTRACT_KEYWORDS = ["合约", "预存", "送手机", "购机", "0元购", "终端", "电子券", "购机款", "得手机", "话费购", "保底", "分期", "违约金"]


def is_contract(name: str, content: str) -> bool:
    text = f"{name} {content}"
    strong = ("合约" in text or "预存" in text) and (
        "手机" in text or "终端" in text or "购机" in text or "电子券" in text or "话费" in text
    )
    return bool(strong)


def contract_desc(name: str, content: str) -> str:
    text = f"{name} {content}"
    for key in ("预存", "合约", "赠送"):
        idx = text.find(key)
        if idx != -1:
            return text[idx : idx + 120]
    return ""


async def run() -> list[dict[str, Any]]:
    from playwright.async_api import async_playwright

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox", "--disable-blink-features=AutomationControlled"])
        ctx = await browser.new_context(user_agent=UA, viewport={"width": 1440, "height": 900}, locale="zh-CN")
        page = await ctx.new_page()
        await page.goto(URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(20000)

        results: list[dict[str, Any]] = []
        for range_tab, region in (("全网资费", "全国"), ("北京资费", "北京")):
            await page.evaluate(
                """(label) => {
                    const els = [...document.querySelectorAll('.range-tab')];
                    const t = els.find(e => (e.innerText||'').trim() === label);
                    if (t) t.click();
                }""",
                range_tab,
            )
            await page.wait_for_timeout(8000)
            # scroll step by step, collecting cards at every stop (virtual scrolling)
            collected: list[str] = []
            prev = 0
            for _ in range(20):
                raw_cards = await extract_cards(page)
                for text in raw_cards:
                    if text not in collected:
                        collected.append(text)
                await page.mouse.wheel(0, 1800)
                await page.wait_for_timeout(1000)
                cur = await page.evaluate("() => document.body.innerText.length")
                if cur == prev and not raw_cards:
                    break
                prev = cur
            raw_cards = await extract_cards(page)
            for text in raw_cards:
                if text not in collected:
                    collected.append(text)
            print(f"  {range_tab}: {len(collected)} cards")
            for text in collected:
                card = parse_card(text)
                if card:
                    card["region"] = region
                    results.append(card)
        await browser.close()
    return results


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="data/mobile.json")
    parser.add_argument("--min-records", type=int, default=20)
    args = parser.parse_args()

    import asyncio

    rows = asyncio.run(run())
    if len(rows) < args.min_records:
        print(f"FAIL: only {len(rows)} rows (< {args.min_records})", file=sys.stderr)
        return 2

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(rows, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"OK: {len(rows)} rows -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
